### ISSUE TITLE
Voot Not Working 

### ISSUE THREAD

**Issue by superman-enamy** [akashrchandran/Account_checkbot#1]
I Checked working voot Account With !voo Commands but Its Not sending as Working

**Comment by akashrchandran** [comment]
It seems to work fine, could you recheck once again. And if you're getting the below error message


![image](https://user-images.githubusercontent.com/78685510/230672607-4128154d-b3f3-4659-bccb-55f549f01930.png)


Then there is no problem with the script, rather it's Voot who are blocking login requests from non-Indian IP. You can bypass the problem either by localhosting the bot or you can, buy an India based server.
